/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_springfieldusa_io_serial_IOStream */

#ifndef _Included_net_springfieldusa_io_serial_IOStream
#define _Included_net_springfieldusa_io_serial_IOStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_springfieldusa_io_serial_IOStream_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    read
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_net_springfieldusa_io_serial_IOStream_read
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    write
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_net_springfieldusa_io_serial_IOStream_write
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    flush
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_flush
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    setBaud
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_setBaud
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    setParity
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_setParity
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    setDataBits
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_setDataBits
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    setStopBits
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_setStopBits
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    setUseFlowControl
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_setUseFlowControl
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    setReadMode
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_setReadMode
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    getStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_springfieldusa_io_serial_IOStream_getStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_springfieldusa_io_serial_IOStream
 * Method:    dumpConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_springfieldusa_io_serial_IOStream_dumpConfig
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
